REPORT RSRRNAME.

*..............................................................*
*  RELEASE........: 740 SUPPORT PACKAGE 15                                                                                                 "005
*  REPORT.........: REP_20221126133223                                                                                                     "010
*  MANDT..........: 040                                                                                                                    "015
*  INFOCUBE.......: Z_FIO004                                                                                                               "020
*  COMPUID........: 00O2TRA79KRCE34XNH0E060WM                                                                                              "025
*  REPUID.........: 00O2TRA79KRCE34XNJJMT29LI                                                                                              "030
*  GENERATED BY...: HXS0615                                                                                                                "035
*  HOST...........: STR-S-BHAP01                                                                                                           "040
*  DATE...........: 26.11.2022                                                                                                             "045
*  TIME...........: 08:36:12                                                                                                               "050
*  TIMESTAMP......:             0                                                                                                          "055
*  TIMESTAMP_META.: 20201006163213                                                                                                         "060
*...............................................................*
*  ATTENTION: Do NOT use any class references here without prior
*  checking the impact on D010TAB references !!
*  use narrow interfaces instead
*
* select master, count(*) as CNT from d010tab A join
*   RSSGTPDIR B on A.master = B.PROGNAME
*   where A.master like 'GP%' and B.PROGCLASS = 'RSR_RECHERCHE_SUBRP'
*   group by master order by CNT desc
*...............................................................*
TYPE-POOLS: RRKG, SYDES.


TYPES: BEGIN OF G_S_DATA_CORE,
         _FEMS TYPE I,         "RRKG_C_SPECIAL_FIELDS-FEMS "H1660136
         Z____028_SUM  TYPE ROWCOUNT_BW,                                                                                                   "090
       END OF G_S_DATA_CORE.
TYPES: BEGIN OF G_S_DATA, "AN INCLUDE FOR THE COMPONENTS OF G_S_DATA_CORE CAN'T BE USED DUE TO TECHNICAL REASONS (TREX, ...)
         S____178 TYPE RSSID,                                                                                                              "075
         S____2119 TYPE RSSID,                                                                                                             "075
         S____2192 TYPE RSSID,                                                                                                             "075
         S____2491 TYPE RSSID,                                                                                                             "075
         S____2492 TYPE RSSID,                                                                                                             "075
         K____2119(000001) TYPE C,                                                                                                         "080
         K____178(000004) TYPE C,                                                                                                          "080
         K____2192(000005) TYPE N,                                                                                                         "080
         K____2492(000025) TYPE C,                                                                                                         "080
         K____2491(000012) TYPE C,                                                                                                         "080
         _FEMS TYPE I,         "RRKG_C_SPECIAL_FIELDS-FEMS "H1660136
         Z____028_SUM  TYPE ROWCOUNT_BW,                                                                                                   "090
       END OF G_S_DATA.

TYPES: BEGIN OF G_S_KENNZ,
         Z____028_SUM__W_ TYPE RSROA_DF,                                                                                                   "100
       END OF G_S_KENNZ.

FIELD-SYMBOLS: <G_S_DATA_S____178>   TYPE RSSID.                                                                                           "075
FIELD-SYMBOLS: <G_S_DATA_S____2119>   TYPE RSSID.                                                                                          "075
FIELD-SYMBOLS: <G_S_DATA_S____2192>   TYPE RSSID.                                                                                          "075
FIELD-SYMBOLS: <G_S_DATA_S____2491>   TYPE RSSID.                                                                                          "075
FIELD-SYMBOLS: <G_S_DATA_S____2492>   TYPE RSSID.                                                                                          "075
FIELD-SYMBOLS: <G_S_DATA_K____2119>   TYPE C.                                                                                              "080
FIELD-SYMBOLS: <G_S_DATA_K____178>   TYPE C.                                                                                               "080
FIELD-SYMBOLS: <G_S_DATA_K____2192>   TYPE N.                                                                                              "080
FIELD-SYMBOLS: <G_S_DATA_K____2492>   TYPE C.                                                                                              "080
FIELD-SYMBOLS: <G_S_DATA_K____2491>   TYPE C.                                                                                              "080


TYPES: BEGIN OF G_S_Q,
         INTF TYPE RSCUBESVINTFORMAT,
       END OF G_S_Q.

TYPES: BEGIN OF G_S_C,
         DUMMY(1) TYPE C,                                                                                                                  "125
       END OF G_S_C.

TYPES: G_XFEMS(1) TYPE X, G_XCHANMID(12) TYPE X.                                                                                           "130
TYPES: G_XSNID(1) TYPE X.                                                                                                                  "135
DATA: G_XWGR(1) TYPE X.                                                                                                                    "140
DATA: G_XWGR_MASK LIKE G_XWGR, G_XWGR_MASK_CUID LIKE G_XWGR, G_XWGR_MASK_ALL LIKE G_XWGR, G_BIT TYPE I.
CONSTANTS: GC_XWGR_EMPTY LIKE G_XWGR VALUE IS INITIAL.
TYPES: BEGIN OF G_S_F,
         DUMMY(1) TYPE C,                                                                                                                  "145
       END OF G_S_F.

DATA: BEGIN OF G_S_FLAG,
        C TYPE RS_BOOL,                                                                                                                    "165
      END OF G_S_FLAG.
CONSTANTS: BEGIN OF G_S_D001_C,                                                                                                            "880
        INI    TYPE RSROA_DF_SHORT VALUE RRKG_C_EPSILON,                                                                                   "880
        W001   TYPE RSROA_DF_SHORT VALUE RRKG_C_EPSILON,                                                                                   "880
      END OF G_S_D001_C.                                                                                                                   "880
DATA: G_S_D000_001 LIKE G_S_D001_C.                                                                                                        "175
TYPES: G_S_D001 LIKE G_S_D000_001.                                                                                                         "195
                                                                                                                                           "195
TYPES: BEGIN OF G_SX_D001,                                                                                                                 "195
         S TYPE G_S_D001,                                                                                                                  "195
       END OF G_SX_D001.                                                                                                                   "195


 TYPES G_CSAP(1) TYPE X.                                                                                                                   "825
 TYPES: BEGIN OF G_S_K,
          DUMMY TYPE CHAR1,
        END OF G_S_K,
        BEGIN OF G_S_FLAGS,
          MOD               TYPE RS_BOOL,
          VIRTUAL_INDICATOR TYPE RS_BOOL,
        END OF G_S_FLAGS,
        BEGIN OF G_SX_CONTENT,
          D001   TYPE G_SX_D001,                                                                                                           "215
          FLAGS   TYPE G_S_FLAGS,
        END OF G_SX_CONTENT,
        BEGIN OF G_SX_S,
          K       TYPE G_S_K,
          CONTENT TYPE G_SX_CONTENT,
        END OF G_SX_S.
 FIELD-SYMBOLS <G_SX_CONTENT> TYPE G_SX_CONTENT.

 TYPES: BEGIN OF G_SX_GVAR,
          DUMMY(1),
        END OF G_SX_GVAR.

 TYPES: BEGIN OF G_SX_NB,
          DUMMY(1) TYPE C,                                                                                                                 "260
        END OF G_SX_NB.

 FIELD-SYMBOLS: <G_FACTOR_C> TYPE C.



DATA: G_C_XFEMS_000A000 TYPE G_XFEMS. "930

INCLUDE RSRDATA0.

DATA: BEGIN OF P_S_SXF,
         SID    TYPE RSSID,
         XFEMS TYPE G_XFEMS,
      END OF P_S_SXF.
TYPES: G_TS_SXF LIKE SORTED TABLE OF P_S_SXF WITH UNIQUE KEY SID.

TYPES: BEGIN OF G_SX_G,
         GVAR      TYPE G_SX_GVAR,
         NB        TYPE G_SX_NB,
         XSNID0    TYPE G_XSNID,
       END OF G_SX_G.

FIELD-SYMBOLS: <G> TYPE G_SX_G.

DEFINE AGGRGEN_SUM_001.                                                                                                                    "845
  ADD: &1-INI TO &2-INI                                                                                                                    "845
      ,&1-W001 TO &2-W001                                                                                                                  "845
      .                                                                                                                                    "845
END-OF-DEFINITION.                                                                                                                         "845




INCLUDE RSRMAINT.
*--------------------------------------------------------------*
FORM INIT_CONSTANTS.
  PERFORM INIT_PACKAGE.
  PERFORM SET_XFEMSBIT. G_C_XFEMS0 = 1.
ENDFORM.
*--------------------------------------------------------------*
FORM INIT_PACKAGE.
  G_S_D000_001 = G_S_D001_C.                                                                                                               "175
  G_S_KENNZ_C-Z____028_SUM__W_ = RRKG_C_EPSILON.                                                                                           "415
ENDFORM.

*--------------------------------------------------------------*
FORM VRNID_FUELLEN.                          "#EC CALLED
   DATA: L_VRNID TYPE RRVRNID.
 ENDFORM.
*--------------------------------------------------------------*
FORM ASSIGN_VARIABLEN.          "#EC NEEDED
  DATA: L_I TYPE I.
ENDFORM.
*------------------------------------------------------------*
FORM ASSIGN_BU USING I_TSX_BU_GRAIN_CLASS TYPE RSR_TSX_BU_GRAIN_CLASS.
  STATICS: P_SX_BU_GRAIN_CLASS TYPE RSR_SX_BU_GRAIN_CLASS.
ENDFORM.
*--------------------------------------------------------------*
FORM SELECT_0 CHANGING C_T_DATA TYPE STANDARD TABLE.
  LOOP AT C_T_DATA INTO <G_S_DATA>.
    PERFORM SELECT_1.
  ENDLOOP.
ENDFORM.
*--------------------------------------------------------------*
FORM SELECT_1.
  PERFORM SELECT_2.                                                                                                                        "505
ENDFORM.
*--------------------------------------------------------------*
FORM SELECT_2.

  CLEAR: <G_SX_S_DATA>, G_S_Q.
  MOVE-CORRESPONDING <G_S_DATA> TO <G_S_K>.
  MOVE-CORRESPONDING <G_S_DATA> TO <G_S_KENNZ>.
  IF G_S_Q NE G_S_QCF-Q.
    PERFORM GET_FACTOR.
  ENDIF.
  PERFORM SELECT_4.
ENDFORM.
*... NUR STRUCTUR                                                                                                                          "175
DEFINE SET_D001.                                      "155                                                                                 "175
  IF <G_SX_CONTENT>-D001-S-INI IS INITIAL.                                                                                                 "175
    <G_SX_CONTENT>-D001-S = G_S_D000_001.                                                                                                  "175
  ELSE.                                                                                                                                    "175
    AGGRGEN_SUM_001 G_S_D000_001 <G_SX_CONTENT>-D001-S.                                                                                    "175
  ENDIF.                                                                                                                                   "175
  G_S_D000_001 = G_S_D001_C.                                                                                                               "175
END-OF-DEFINITION.                                                                                                                         "175

*--------------------------------------------------------------*
FORM SELECT_4.

  CLEAR G_XWGR.                                                                                                                            "540
  PERFORM CHECK.                                                                                                                           "540
  G_XWGR = G_XWGR BIT-AND G_XWGR_MASK_ALL.                                                                                                 "540
  CHECK G_XWGR IS NOT INITIAL OR G_ONLYKEYS = RS_C_TRUE.                                                                                   "540
  G_XWGR = G_XWGR BIT-AND G_XWGR_MASK.                                                                                                     "540
  G_R_QCUBE_DATA_PCK_GEN->SET_COMMIT( RRKG_C_SPCOMMIT-FILLED ).
  IF G_S_QCF-CMESS EQ RRKG_C_CMESS-ERROR.
    PERFORM CU_MESS_SEND.
  ENDIF.
  READ TABLE <G_TX_S> FROM <G_SX_S_DATA> USING KEY (rrkg_c_sp_sec_key) ASSIGNING <G_SX_S>.
  IF SY-SUBRC GT 0.
    INSERT <G_SX_S_DATA> INTO TABLE <G_TX_S> ASSIGNING <G_SX_S>.
  ENDIF.
  ASSIGN COMPONENT 2 OF STRUCTURE <G_SX_S> TO <G_SX_CONTENT>.
IF G_XWGR+0(1) O RRKG_C_BX-X1.   SET_D001.  ENDIF.                                                                                         "530

ENDFORM.

*--------------------------------------------------------------*                                                                           "585
FORM MOVE_Z_SP_0001                                           "1                                                                           "585
  .                                                              "1                                                                        "585
        G_S_D000_001-W001 =  G_S_KENNZ-Z____028_SUM__W_ .                          "6                                                      "585
        G_XWGR+0(1) = G_XWGR+0(1) BIT-OR RRKG_C_BX-X1.   "8                                                                                "585
  ENDFORM.                                                       "I                                                                        "585
*--------------------------------------------------------------*
FORM CHECK.
  STATICS: P_FEMS TYPE I, P_XFEMS TYPE G_XFEMS.                                                                                            "595
  DATA: L_OFFS TYPE I.                                                                                                                     "595
  IF <G_S_DATA_FEMS> IS INITIAL.                                                                                                           "595
    P_XFEMS = G_SEL_FEMS.                                                                                                                  "595
    PERFORM MOVE_Z_SP_0001.                                                                                                                "605
    RETURN ##STMNT_EXIT.                                                                                                                   "595
    PERFORM DEBUG_XFEMS. "FOR DEBUGGING ONLY                                                                                               "595
  ELSE.                                                                                                                                    "595
    IF     <G_S_DATA_FEMS> LT 10000.                                                 PERFORM CHECK_FEMS USING <G_S_DATA_FEMS>.             "595
    ELSEIF <G_S_DATA_FEMS> LT 1000000000.                                                                                                  "595
      P_FEMS = <G_S_DATA_FEMS> MOD 10000.                                            PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> DIV 10000.                                            PERFORM CHECK_FEMS USING P_FEMS.                      "595
    ELSEIF <G_S_DATA_FEMS> LT 2000000000.                                                                                                  "595
      P_FEMS = <G_S_DATA_FEMS> MOD 1000. <G_S_DATA_FEMS> = <G_S_DATA_FEMS> DIV 1000. PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> MOD 1000. <G_S_DATA_FEMS> = <G_S_DATA_FEMS> DIV 1000. PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> MOD 1000.                                             PERFORM CHECK_FEMS USING P_FEMS.                      "595
    ELSE.                                                                                                                                  "595
      P_FEMS = <G_S_DATA_FEMS> MOD 100.  <G_S_DATA_FEMS> = <G_S_DATA_FEMS> DIV 100.  PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> MOD 100.  <G_S_DATA_FEMS> = <G_S_DATA_FEMS> DIV 100.  PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> MOD 100.  <G_S_DATA_FEMS> = <G_S_DATA_FEMS> DIV 100.  PERFORM CHECK_FEMS USING P_FEMS.                      "595
      P_FEMS = <G_S_DATA_FEMS> MOD 100.                                              PERFORM CHECK_FEMS USING P_FEMS.                      "595
    ENDIF.                                                                                                                                 "595
  ENDIF.                                                                                                                                   "595
ENDFORM.
*--------------------------------------------------------------*                                                                           "595
FORM CHECK_FEMS USING I_FEMS TYPE I.
  STATICS: P_BIT TYPE I.                                                                                                                   "595
    IF G_CHECK_BIA EQ RS_C_TRUE.                                                                                                           "595
    IF G_KIDSEL EQ RS_C_TRUE. GET BIT I_FEMS OF G_SEL_FEMS INTO P_BIT. CHECK P_BIT = 1. ENDIF.                                             "595
    IF G_CHECK_BIA_N EQ RS_C_TRUE.                                                                                                         "595
    ENDIF. ENDIF.                                                                                                                          "595
  PERFORM I_FEMS OF           " REP I_FEMS = 2                                                                                             "615
          MOVE_Z_SP_0001                                                                                                                   "620
          DEBUG_XFEMS.                                                                                                                     "615
ENDFORM.                      " NOW LOOK AT G_TSX_XFEMS
*--------------------------------------------------------------*
FORM SET_XFEMSBIT.
  FIELD-SYMBOLS: <L_X> TYPE X.                                                                                                             "640
  ASSIGN  G_C_XFEMS_000A000+000(01) TO <L_X>. <L_X> = '80' .                                                                               "640
ENDFORM.

*--------------------------------------------------------------*
FORM GET_PART USING    I_SX_SPLITPACK TYPE RSDR0_SX_SPLITPACK "#EC CALLED
                       I_TH_CHARET    TYPE RSDR0_TH_CHARET
                       I_R_MOVE_TYPE  TYPE REF TO CL_ABAP_STRUCTDESCR
                       I_TH_SFC       TYPE RSDD_TH_SFC
                       I_TH_SFK       TYPE RSDD_TH_SFK
                       I_S_DATA       TYPE ANY
                       I_CHECK0       TYPE RS_BOOL
                       I_XFEMS        TYPE XSTRING
                       I_TS_CHXFEMS   TYPE RSDD_TS_CHXFEMS
                       I_S_minmax     type rsdd_S_minmax
                       I_XWGR         TYPE XSTRING
                       I_XWGR_ALL      TYPE XSTRING
                       I_XWGR_CUID    TYPE XSTRING
                       I_ONLYKEYS     TYPE RRONLYKEYS
                       I_1CUDIM_ACTIVE TYPE RS_BOOL
                       I_TS_CM_BUF     TYPE RRKG_TS_CURMEM_BUFFER.

  DATA: L_S_CHARET    TYPE RSDR0_S_CHARET,
        L_S_CHXFEMS   TYPE RSDD_S_CHXFEMS,
        L_R_KENNZ     TYPE REF TO CL_ABAP_STRUCTDESCR,
        L_R_SX_S_DATA TYPE REF TO DATA,
        L_R_S_DATA    TYPE REF TO DATA.
  DATA: L_XFEMS       TYPE G_XFEMS.                                                                                                        "595

  FIELD-SYMBOLS: <L_S_DATA_WIDE> TYPE DATA.

  G_CHECK0   = I_CHECK0.
  IF I_SX_SPLITPACK-TS_PARTPROV IS INITIAL.
    G_PARTPROV = I_SX_SPLITPACK-PARTPROV.
    G_PSID     = I_SX_SPLITPACK-PARTPROV_SID.
    G_MULTIPROV = RS_C_FALSE.
  ELSE.
    CLEAR: G_PARTPROV, G_PSID.
    G_MULTIPROV = RS_C_TRUE.
  ENDIF.
  G_INTF     = I_SX_SPLITPACK-INTFORMAT.
  G_NCUM     = I_SX_SPLITPACK-NCUM_VALUES.
  PERFORM GET_KENNZ_TYPE(SAPSRRK0) USING    G_S_KENNZ
                                            I_TH_SFK
                                   CHANGING L_R_KENNZ.
  G_S_KENNZ = G_S_KENNZ_C.
  ASSIGN G_S_KENNZ TO <G_S_KENNZ> CASTING TYPE HANDLE L_R_KENNZ.
  L_R_S_DATA = G_R_CALLBACK->GET_REF_TO_S_DATA( ).
  ASSIGN L_R_S_DATA->* TO <L_S_DATA_WIDE>.
  ASSIGN I_S_DATA TO <G_S_DATA>.
  IF I_SX_SPLITPACK-NCUM_VALUES IS NOT INITIAL.
    ASSIGN <G_S_DATA> TO <L_S_DATA_WIDE>.
  ENDIF.
  CREATE DATA L_R_SX_S_DATA LIKE LINE OF <G_TX_S>.
  ASSIGN L_R_SX_S_DATA->* TO <G_SX_S_DATA>.
  ASSIGN COMPONENT 1 OF STRUCTURE <G_SX_S_DATA> TO <G_S_K> CASTING TYPE HANDLE I_R_MOVE_TYPE.
  IF G_CHECK0 EQ RS_C_TRUE.
  ENDIF.
  ASSIGN COMPONENT RRKG_C_SPECIAL_FIELDS-FEMS OF STRUCTURE <G_S_DATA> TO <G_S_DATA_FEMS>.

  IF I_TS_CHXFEMS IS NOT INITIAL.
  ENDIF.
  G_SEL_FEMS  = I_SX_SPLITPACK-SEL_FEMS.                                                                                                   "595
  CLEAR: G_CHECK_BIA, G_CHECK_BIA_N.                                                                                                       "595
  IF I_SX_SPLITPACK-FEMS_FILLED NA ' X'. G_CHECK_BIA_N = RS_C_TRUE. ENDIF.                                                                 "595
  IF I_XFEMS IS NOT INITIAL.                                                                                                               "595
    G_SEL_FEMS = G_SEL_FEMS BIT-AND I_XFEMS.                                                                                               "595
    L_XFEMS = G_SEL_FEMS BIT-AND G_C_XFEMS_000A000.                                                                                        "595
    IF G_SEL_FEMS NE L_XFEMS. G_KIDSEL = RS_C_TRUE. ENDIF.                                                                                 "595
  ENDIF.                                                                                                                                   "595
  IF G_KIDSEL EQ RS_C_TRUE OR G_CHECK_BIA_N EQ RS_C_TRUE. G_CHECK_BIA = RS_C_TRUE. ENDIF.                                                  "595
  G_XWGR_MASK = I_XWGR.
  G_XWGR_MASK_ALL = I_XWGR_ALL.
  G_XWGR_MASK_CUID = I_XWGR_CUID.
  G_ONLYKEYS  = I_ONLYKEYS.


  PERFORM INIT_PACKAGE.
ENDFORM.
*---------------------------------------------------------------*
FORM COLLECT_S USING    I_TS_WGR TYPE RRKG_TS_WGR_COLLECT
                        I_ALWAYS_AGGR_TLENG TYPE RS_BOOL
               CHANGING C_SX_CONTENT_I TYPE G_SX_CONTENT
                        C_SX_CONTENT_C TYPE G_SX_CONTENT
  .
  STATICS: L_S_WGR LIKE LINE OF I_TS_WGR.

  LOOP AT I_TS_WGR INTO L_S_WGR.
    CASE L_S_WGR-WGR.
      WHEN 001. "... NUR STRUC                                                                                                             "715
    IF C_SX_CONTENT_I-D001-S-INI GT 0.                                                                                                     "715
      IF C_SX_CONTENT_C-D001-S-INI IS INITIAL.                                                                                             "715
        C_SX_CONTENT_C-D001-S = C_SX_CONTENT_I-D001-S.                                                                                     "715
      ELSE.                                                                                                                                "715
        AGGRGEN_SUM_001 C_SX_CONTENT_I-D001-S C_SX_CONTENT_C-D001-S.                                                                       "715
      ENDIF.                                                                                                                               "715
    ENDIF.                                                                                                                                 "715

      WHEN OTHERS.
        G_R_CALLBACK->X_MESSAGE( 'COLLECT_S-WGR-' ).
    ENDCASE.
  ENDLOOP.


ENDFORM.

FORM COLLECT_S_BLFV_FLAGS USING    I_SX_CONTENT TYPE G_SX_CONTENT
                          CHANGING C_SX_CONTENT TYPE G_SX_CONTENT.
ENDFORM.
*--------------------------------------------------------------*
FORM FACTOR_ASSIGN USING I_S_F TYPE G_S_F.

  STATICS: S_OK TYPE RS_BOOL.
     CHECK S_OK EQ RS_C_FALSE.
  S_OK = RS_C_TRUE.
ENDFORM.
*--------------------------------------------------------------*

*------------------------------------------------------*
FORM DEBUG_XFEMS.
  PERFORM DEBUG_XFEMS_01 USING 'G_SEL_FEMS'           G_SEL_FEMS.
  PERFORM DEBUG_XFEMS_01 USING 'G_C_XFEMS_000A000' G_C_XFEMS_000A000.                                                                      "815
  BREAK-POINT. G_TX_XFEMS = G_TX_XFEMS.        "#EC *
ENDFORM.
FORM DEBUG_XWGR.
  PERFORM DEBUG_XFEMS_01 USING 'G_XWGR' G_XWGR.
ENDFORM.
FORM AGGR_PDQ.
ENDFORM.


*.. The following subroutine is for internal (FuGr RSSG) use only! ..*


FORM _RSSG_PROGRAM_LOADCHECK
     CHANGING E_S_PDIR TYPE RSSGTPDIR
              E_FOUND  TYPE FLAG. "#EC CALLED
CONSTANTS:
BEGIN OF _RSSG_C_PCLA,
  PROGCLASS TYPE  RSSGTPCLA-PROGCLASS
    VALUE 'RSR_RECHERCHE_SUBRP',
  CLIDEP TYPE  RSSGTPCLA-CLIDEP
    VALUE ' ',
  GENFLAG TYPE  RSSGTPCLA-GENFLAG
    VALUE 'X',
  SUBC TYPE  RSSGTPCLA-SUBC
    VALUE 'S',
  TEMPLATE TYPE  RSSGTPCLA-TEMPLATE
    VALUE 'RSRDUMMY',
END   OF _RSSG_C_PCLA,

BEGIN OF _RSSG_C_PDIR,
  UNI_IDC25 TYPE  RSSGTPDIR-UNI_IDC25
    VALUE '00O2TRA79KRCE34XO9Y0CBCWN',
  CLIENT TYPE  RSSGTPDIR-CLIENT
    VALUE ' ',
  PROGCLASS TYPE  RSSGTPDIR-PROGCLASS
    VALUE 'RSR_RECHERCHE_SUBRP',
  PROGNAME TYPE  RSSGTPDIR-PROGNAME
    VALUE 'GP00O2TRA79KRCE34XO9Y0CBCWN',
  CREUSER TYPE  RSSGTPDIR-CREUSER
    VALUE 'HXS0615',
  CRETSTMP TYPE  RSSGTPDIR-CRETSTMP
    VALUE 20221126133614,
  GENUSER TYPE  RSSGTPDIR-GENUSER
    VALUE 'HXS0615',
  GENTSTMP TYPE  RSSGTPDIR-GENTSTMP
    VALUE 20221126133614,
  GENRELEASE TYPE  RSSGTPDIR-GENRELEASE
    VALUE '740',
  GENSTATUS TYPE  RSSGTPDIR-GENSTATUS
    VALUE '00',
  TEMPLATE TYPE  RSSGTPDIR-TEMPLATE
    VALUE 'RSRDUMMY',
  UPDUSERTPL TYPE  RSSGTPDIR-UPDUSERTPL
    VALUE 'SAP',
  UPDDATETPL TYPE  RSSGTPDIR-UPDDATETPL
    VALUE '20161201',
  UPDTIMETPL TYPE  RSSGTPDIR-UPDTIMETPL
    VALUE '232423',
  SUBC TYPE  RSSGTPDIR-SUBC
    VALUE 'S',
  WITH_SUBTEMPL TYPE  RSSGTPDIR-WITH_SUBTEMPL
    VALUE ' ',
END   OF _RSSG_C_PDIR.

  MOVE-CORRESPONDING _RSSG_C_PDIR TO E_S_PDIR.
  E_FOUND = 'X'.
ENDFORM.
